"""empty message

Revision ID: 802d90e8cd41
Revises: a5cffa318ac2
Create Date: 2024-08-09 22:38:17.718552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802d90e8cd41'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=250), nullable=True),
    sa.Column('gender', sa.String(length=250), nullable=True),
    sa.Column('hair_color', sa.String(length=250), nullable=True),
    sa.Column('eye_color', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_name', sa.String(length=250), nullable=True),
    sa.Column('climate', sa.String(length=250), nullable=True),
    sa.Column('diameter', sa.String(length=250), nullable=True),
    sa.Column('gravity', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('led_user_id', sa.Integer(), nullable=True),
    sa.Column('led_favorite_characters', sa.Integer(), nullable=True),
    sa.Column('led_favorite_planets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['led_favorite_characters'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['led_favorite_planets'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['led_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('planets')
    op.drop_table('characters')
    # ### end Alembic commands ###
